### PR TITLE
Updating preact version to latest

### PR DESCRIPTION
**Pull request by phdlove42**
This is literally the first PR I've opened to an open source project so if this isn't quite what I should be doing feel free to close this.

In any case, using the visualizer in my project and this looks to be the only package that complains about TypeScript 2.4.x, so I thought I'd see if I could update it myself. I ran the sample included in the package.json and I believe it's fine.

Let me know how that works I suppose.

### CODE REVIEW

**Comment by elboman** [comment]
Awesome, thanks for the PR! I tested and it works fine, the only problem is the `yarn.lock` needs to be updated as well.

If you could commit the updated file I'be happy to merge.

**Comment by phdlove42** [comment]
@elboman updated the file, sorry for the delay.

**Comment by christopherthielen** [comment]
Looks good, thanks!

**Comment by phdlove42** [comment]
Glad to contribute!

**Pull request merged**
